server:
  port: 8087

spring:
  application:
    name: locadora-backend
  datasource:
    url: jdbc:postgresql://localhost:5439/locadora_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
